name: OWASP Dependency Check (.NET)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    name: Scan dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependency-Check
      run: |
             wget https://github.com/jeremylong/DependencyCheck/releases/latest/download/dependency-check.zip
             unzip dependency-check.zip

    - name: Run scan
      run: |
        ./dependency-check/bin/dependency-check.sh \
          --project "cas-dotnet-sdk" \
          --scan . \
          --format "HTML" \
          --out reports
