name: OWASP Dependency Check (.NET)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    name: Scan dependencies
    runs-on: ubuntu-latest

    steps:

    - name: Install Dependency-Check
      run: |
             curl -Ls https://github.com/dependency-check/DependencyCheck/releases/download/v12.2.0/dependency-check-12.2.0-release.zip -o dependency-check-12.2.0-release.zip
             unzip dependency-check-12.2.0-release.zip

    - name: Run scan
      run: |
        ./dependency-check-12.2.0-release/bin/dependency-check.sh \
          --project "cas-dotnet-sdk" \
          --scan . \
          --format "HTML" \
          --out reports
