# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout cas-dotnet-sdk
      uses: actions/checkout@v3
    - name: Checkout cas-dotnet-helpers
      uses: actions/checkout@v3
      with:
        repository: Cryptographic-API-Services/cas-dotnet-helpers
        path: D:\a\cas-dotnet-sdk\
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
